version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.20
    - 6.1.21
    - 6.2.0
    - 6.2.2
    - 6.2.5
    - 6.2.8
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.0
    - 6.2.1
    - 6.2.7
  - dependency-name: storybook
    versions:
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
  - dependency-name: antd
    versions:
    - 4.12.3
    - 4.13.1
    - 4.14.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.33
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: gatsby-recipes
    versions:
    - 0.9.1
  - dependency-name: gatsby-plugin-sass
    versions:
    - 3.2.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.11.0
  - dependency-name: gatsby
    versions:
    - 2.32.4
  - dependency-name: update-notifier
    versions:
    - 5.1.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby-cli
    versions:
    - 2.19.1
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
